apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dd-pvc
  namespace: jimyag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Pod
metadata:
  name: test-dd
  namespace: jimyag
spec:
  containers:
  - name: test
    image: alpine:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: data-vol
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      runAsUser: 0  # root for dd access
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: test-dd-pvc
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
